Edi dev
Team-MoXie/InventoryManager pull request #42
Opened 2020-11-12 20:17 UTC by eedom

Create website with a create product form

2020-11-12 20:47 UTC, TrainBuilder commented on CustomerOrders/src/main/java/resources/config.properties
> +
@omnitree Config file got merged again

2020-11-12 23:52 UTC, eedom commented on CustomerOrders/src/main/java/resources/config.properties
> +
I did it because last time I lost it. sorry teams !

2020-11-13 03:24 UTC, TrainBuilder commented
Resolved conflicts. Should merge and run fine now.

2020-11-13 23:07 UTC, omnitree commented on CustomerOrders/src/main/java/team/moxie/servlets/StaticFileServlet.java
> +      }
Avoid empty catches, and also name the exceptions when you are nesting them like this.

2020-11-13 23:09 UTC, omnitree commented on CustomerOrders/src/main/java/team/moxie/Main.java
> +
This likely should be in it's own file.

2020-11-13 23:11 UTC, omnitree requested changes
Check previous comments, mainly the part about moving that tomcat method out of main.

2020-11-19 20:42 UTC, eedom commented on CustomerOrders/src/main/java/team/moxie/servlets/StaticFileServlet.java
> +      }
I made this change

2020-11-19 20:43 UTC, eedom commented on CustomerOrders/src/main/java/team/moxie/Main.java
> +
I made the request change

2020-11-30 09:51 UTC, omnitree approved these changes

2020-11-30 09:52 UTC, merged